version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000" # Maps container port 3000 to host port 3000
    environment:
      - NODE_ENV=development
      - USER=postgres # From PostgreSQL setup
      - PASSWORD=3179
      - HOST=localhost
      - DATABASE=EFdb
      - PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres # Database credentials
      POSTGRES_PASSWORD: 3179
      POSTGRES_DB: EFdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # For persistent database storage

volumes:
  pgdata:
